import { useEffect, useState } from "react";
import { AlertTriangle, Bot, CalendarDays, ChevronLeft, FileText, FolderKanban, FolderTree, LayoutDashboard, ListTodo, LogOut, Menu, RefreshCw, Search, Settings, ShieldCheck } from "lucide-react";

type Project = { id: number; name: string };
type Summary = { attention:number; open_tasks:number; overdue_tasks:number; open_risks:number; pending_decisions:number; drafts:number; documents:number };
type DocumentCard = { document_id?:number; name:string; tasks:number; risks:number; decisions:number; drafts:number; attention:number };
type AnalysisResult = { status:string; documents?:number; tasks?:number; risks?:number; drafts?:number; error?:string };
type Snapshot = { id:number; status:string; item_count:number; source_folder:string; source_external_id:string; is_primary:boolean; analyzed:boolean; analysis_status?:string; analysis_result?:AnalysisResult; analysis_error?:string; created_at:string; completed_at?:string };
type DriveFolder = { id:string; name:string; modifiedTime?:string; registered:boolean; is_primary:boolean; analyzed:boolean; analysis_status?:string; analysis_result?:AnalysisResult; analysis_error?:string; snapshot_id?:number; snapshot_status?:string; item_count?:number };

const items = [
  [LayoutDashboard,"Рабочий центр"], [FolderKanban,"Проекты"], [FileText,"Документы"],
  [ListTodo,"Задачи"], [AlertTriangle,"Риски и решения"], [Bot,"AI Secretary"],
  [CalendarDays,"Интеграции"], [ShieldCheck,"Журнал"], [Settings,"Настройки"],
] as const;

async function api(path:string, options:RequestInit={}) {
  const token=sessionStorage.getItem("pu_token");
  const response=await fetch(path,{...options,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})}});
  const body=await response.json().catch(()=>({}));
  if(!response.ok) throw new Error(body.detail||`HTTP ${response.status}`);
  return body;
}

function Login({onDone}:{onDone:()=>void}){
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [error,setError]=useState("");
  async function submit(){try{const d=await api("/auth/login",{method:"POST",body:JSON.stringify({email,password})});sessionStorage.setItem("pu_token",d.access_token);onDone()}catch(e){setError((e as Error).message)}}
  return <div className="login-page"><div className="login-card"><div className="brand-mark">PU</div><h1>Вход в PU Workspace</h1><p>Единое рабочее пространство проектов и документов</p><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email"/></label><label>Пароль<input value={password} onChange={e=>setPassword(e.target.value)} type="password" onKeyDown={e=>e.key==="Enter"&&submit()}/></label><button onClick={submit}>Войти</button>{error&&<div className="error">{error}</div>}<a href="/">Открыть прежний интерфейс</a></div></div>
}

export function App(){
  const [ready,setReady]=useState(false),[collapsed,setCollapsed]=useState(false),[mobile,setMobile]=useState(false);
  const [projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState(0),[summary,setSummary]=useState<Summary|null>(null),[documents,setDocuments]=useState<DocumentCard[]>([]),[snapshots,setSnapshots]=useState<Snapshot[]>([]),[folders,setFolders]=useState<DriveFolder[]>([]),[showSources,setShowSources]=useState(false),[busyFolder,setBusyFolder]=useState(""),[busyAll,setBusyAll]=useState(false),[notice,setNotice]=useState(""),[error,setError]=useState("");
  async function load(){try{setError("");const p=await api("/projects/");setProjects(p.projects);const id=projectId||p.projects[0]?.id||0;if(id){setProjectId(id);const [d,s]=await Promise.all([api(`/dashboard/project?project_id=${id}`),api(`/projects/${id}/snapshots`)]);setSummary(d.summary);setDocuments(d.documents);setSnapshots(s.snapshots)}}catch(e){setError((e as Error).message)}}
  async function openSources(){try{setError("");const d=await api(`/projects/${projectId}/source-folders/discover`);setFolders(d.folders);setShowSources(true)}catch(e){setError((e as Error).message)}}
  async function queueFolder(folder:DriveFolder){try{const queued=await api(`/projects/${projectId}/source-folders/${folder.id}/snapshot-queue`,{method:"POST"});setFolders(items=>items.map(item=>item.id===folder.id?{...item,registered:true,snapshot_id:queued.id,snapshot_status:queued.status,item_count:0}:item));await load()}catch(e){setError((e as Error).message)}}
  async function makePrimary(folder:DriveFolder){try{setBusyFolder(folder.id);setError("");await api(`/projects/${projectId}/source-folders/${folder.id}/primary`,{method:"POST"});setFolders(items=>items.map(item=>({...item,is_primary:item.id===folder.id})));setSnapshots(items=>items.map(item=>({...item,is_primary:item.source_external_id===folder.id})));setNotice(`${folder.name} назначена основной рабочей папкой`)}catch(e){setError((e as Error).message)}finally{setBusyFolder("")}}
  async function analyzeFolder(folder:DriveFolder){if(!folder.snapshot_id)return;try{setBusyFolder(folder.id);setError("");setNotice("");const result=await api(`/projects/${projectId}/snapshots/${folder.snapshot_id}/analyze`,{method:"POST"});if(result.already_analyzed){setFolders(items=>items.map(item=>item.id===folder.id?{...item,analyzed:true}:item));setNotice(`${folder.name} уже проанализирована`)}else{setFolders(items=>items.map(item=>item.id===folder.id?{...item,analysis_status:"analyzing"}:item));setNotice(`Анализ «${folder.name}» запущен в фоне. Страницу можно закрыть.`)}}catch(e){setError((e as Error).message)}finally{setBusyFolder("")}}
  async function queueAllFolders(){try{setBusyAll(true);setError("");const result=await api(`/projects/${projectId}/source-folders/snapshot-queue-all`,{method:"POST"});setNotice(result.queued?`В очередь добавлено папок: ${result.queued}. Они будут обработаны последовательно.`:"Все доступные папки уже подключены или находятся в очереди.");await openSources();await load()}catch(e){setError((e as Error).message)}finally{setBusyAll(false)}}
  useEffect(()=>{api("/auth/me").then(()=>setReady(true)).catch(()=>setReady(false))},[]);
  useEffect(()=>{if(ready)load()},[ready,projectId]);
  useEffect(()=>{if(!ready||!snapshots.some(item=>item.status==="building"))return;const timer=window.setInterval(load,5000);return()=>window.clearInterval(timer)},[ready,projectId,snapshots.some(item=>item.status==="building")]);
  useEffect(()=>{if(!ready||!showSources||!folders.some(item=>item.snapshot_status==="building"||item.analysis_status==="analyzing"))return;const timer=window.setInterval(()=>{openSources();load()},5000);return()=>window.clearInterval(timer)},[ready,projectId,showSources,folders.some(item=>item.snapshot_status==="building"||item.analysis_status==="analyzing")]);
  if(!ready)return <Login onDone={()=>setReady(true)}/>;
  const metrics=[["Требуют внимания",summary?.attention||0,"warn"],["Открытые задачи",summary?.open_tasks||0,""],["Просрочено",summary?.overdue_tasks||0,"danger"],["Риски",summary?.open_risks||0,"warn"],["Ждут решения",summary?.pending_decisions||0,""],["Документы",summary?.documents||0,""]];
  const latestSnapshot=snapshots.find(item=>item.is_primary)||snapshots[0];
  return <div className="shell">
    <aside className={`${collapsed?"collapsed":""} ${mobile?"mobile-open":""}`}><div className="sidebar-head"><div className="brand-mark">PU</div>{!collapsed&&<strong>PU Workspace</strong>}<button className="icon" onClick={()=>setCollapsed(!collapsed)}><ChevronLeft/></button></div><nav>{items.map(([Icon,label],i)=><button className={i===0?"active":""} key={label} title={label}><Icon/><span>{label}</span></button>)}</nav><div className="profile"><div className="avatar">D</div>{!collapsed&&<div><strong>Администратор</strong><small>Владелец</small></div>}<button className="icon" onClick={()=>{sessionStorage.removeItem("pu_token");setReady(false)}}><LogOut/></button></div></aside>
    <main><header><button className="mobile-menu icon" onClick={()=>setMobile(!mobile)}><Menu/></button><div><h1>Рабочий центр</h1><p>Главное по проекту на сегодня</p></div><div className="header-actions"><div className="search"><Search/><input placeholder="Поиск по проекту"/></div><select value={projectId} onChange={e=>setProjectId(Number(e.target.value))}>{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><button className="icon" onClick={load}><RefreshCw/></button></div></header>
      <section className="content">{error&&<div className="error">{error}</div>}{notice&&<div className="notice">{notice}</div>}<div className="metrics">{metrics.map(([label,value,tone])=><article className={String(tone)} key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</div>
      <div className="grid"><section className="card span-2"><div className="card-head"><div><h2>Что требует внимания</h2><p>Задачи, риски и решения из подтверждённых источников</p></div><button>Открыть реестр</button></div>{summary?.attention?<div className="attention"><AlertTriangle/><div><strong>{summary.attention} пунктов требуют проверки</strong><p>Просрочено задач: {summary.overdue_tasks}; открытых рисков: {summary.open_risks}; решений: {summary.pending_decisions}.</p></div></div>:<div className="empty"><ShieldCheck/><p>Критичных пунктов нет</p></div>}</section>
      <section className="card"><div className="card-head"><div><h2>Быстрые действия</h2><p>Без изменения оригиналов</p></div></div><div className="quick"><a href="/#folderId">Выбрать папку Drive</a><a href="/#chooseLocalFolder">Загрузить папку</a><a href="/#tasksPanel">Открыть задачи</a></div></section>
      {latestSnapshot&&<section className="card span-3 source-card"><div className="source-icon"><FolderTree/></div><div><span className="eyebrow">РАБОЧИЙ ИСТОЧНИК</span><h2>{latestSnapshot.source_folder}</h2><p>Виртуальный снимок №{latestSnapshot.id} · {latestSnapshot.item_count.toLocaleString("ru-RU")} объектов · оригиналы не изменяются</p></div><span className={`source-status ${latestSnapshot.status}`}>{latestSnapshot.status==="ready"?"Снимок готов":latestSnapshot.status}</span><div className="source-actions"><button onClick={openSources}>Все источники</button><a className="source-link" href={`https://drive.google.com/drive/folders/${latestSnapshot.source_external_id}`} target="_blank" rel="noreferrer">Открыть в Google Drive</a></div></section>}
      {showSources&&<section className="card span-3"><div className="card-head"><div><h2>Папки для последовательного разбора</h2><p>Каждая папка получает отдельный виртуальный снимок; файлы не перемещаются.</p></div><div className="source-head-actions"><button className="queue-all" disabled={busyAll} onClick={queueAllFolders}>{busyAll?"Добавление…":"Подготовить все папки"}</button><button onClick={()=>setShowSources(false)}>Закрыть</button></div></div><div className="source-list">{folders.map(folder=><article key={folder.id}><FolderKanban/><div><strong>{folder.name}{folder.is_primary&&<span className="primary-label">Основная</span>}</strong><p>{folder.snapshot_status==="building"?"Создаётся виртуальный снимок…":folder.analysis_status==="analyzing"?`Анализируется в фоне · ${(folder.item_count||0).toLocaleString("ru-RU")} объектов`:folder.analysis_status==="failed"?`Ошибка анализа: ${folder.analysis_error||"можно повторить"}`:folder.analysis_status==="ready"?`Готово: документов ${folder.analysis_result?.documents||0}, задач ${folder.analysis_result?.tasks||0}, рисков ${folder.analysis_result?.risks||0}, черновиков ${folder.analysis_result?.drafts||0}`:folder.snapshot_status==="ready"?`Снимок №${folder.snapshot_id} готов · ${(folder.item_count||0).toLocaleString("ru-RU")} объектов${folder.analyzed?" · проанализирован":""}`:folder.snapshot_status==="failed"?"Ошибка снимка — можно повторить":folder.modifiedTime?`Изменена ${new Date(folder.modifiedTime).toLocaleDateString("ru-RU")}`:"Google Drive"}</p></div><div className="source-row-actions">{folder.registered&&!folder.is_primary&&<button disabled={busyFolder===folder.id} onClick={()=>makePrimary(folder)}>Сделать основной</button>}{folder.snapshot_status==="ready"?<button className="analyze" disabled={busyFolder===folder.id||folder.analyzed||folder.analysis_status==="analyzing"} onClick={()=>analyzeFolder(folder)}>{busyFolder===folder.id||folder.analysis_status==="analyzing"?"Анализ…":folder.analyzed?"Проанализирована":folder.analysis_status==="failed"?"Повторить анализ":"Проанализировать"}</button>:<button disabled={folder.snapshot_status==="building"||busyFolder===folder.id} onClick={()=>queueFolder(folder)}>{folder.snapshot_status==="building"?"В очереди":folder.snapshot_status==="failed"?"Повторить":"Поставить в очередь"}</button>}</div></article>)}</div></section>}
      <section className="card span-3"><div className="card-head"><div><h2>Последние документы</h2><p>Связанные задачи, риски и решения</p></div><button>Все документы</button></div><div className="doc-list">{documents.slice(0,8).map(d=><article key={d.name}><div className="file-icon"><FileText/></div><div><strong>{d.name}</strong><p>Задач {d.tasks} · рисков {d.risks} · решений {d.decisions}</p></div>{d.attention>0&&<span className="pill">Внимание: {d.attention}</span>}</article>)}</div></section></div></section>
    </main>
  </div>
}
